### PR TITLE
Build for Mac.

### PR DESCRIPTION
**Pull request by chrisdembia**
@aymanhab This is a start at building a Mac release. It's not quite working on Travis and it seems unlikely that I will get it working tonight. But I am able to run `build_on_mac.sh` locally to build a release.

### CODE REVIEW

**Comment by aymanhab** [comment]
Thanks @chrisdembia I'll take a look but also keep @jenhicks in the loop since she's waiting on a build to send out with webinar announcement

**Comment by chrisdembia** [comment]
Okay. It took 16 minutes to run the release script on my Mac at lab. So I can run that again once we have a 4.0 tag. When do you plan on creating the tag?

Do you plan to use this repo to build the Windows release? You will have to wait 1.5 hours for the build to finish.

**Comment by chrisdembia** [comment]
Let me know if you want me to create the Mac release locally.

**Comment by chrisdembia** [comment]
This PR also fixes some things in the Windows build script.

**Comment by chrisdembia** [comment]
Woohoo!

**Comment by chrisdembia** [comment]
Now that there's a 4.0 GUI tag, I've started building the Mac release locally. If you have other plans, that's fine.

**Comment by aymanhab** [comment]
@chrisdembia I have no other plans, will let the process go through. Thank you for all your help 🥇

**Pull request merged**
